import type {
  CRMNavigationItemConfig,
  CRMNavigationSectionConfig,
} from "@/types/crm-config";

export const bajajIzcalliNavigationSections: CRMNavigationSectionConfig[] = [
  {
    id: "sales",
    label: "Ventas",
    order: 1,
    visible: true,
  },
  {
    id: "commercial-operation",
    label: "Operación comercial",
    order: 2,
    visible: true,
  },
  {
    id: "administration",
    label: "Administración",
    order: 3,
    visible: true,
    allowedRoles: ["owner", "admin", "manager"],
  },
  {
    id: "coming-soon",
    label: "Próximamente",
    order: 4,
    visible: true,
  },
];

export const bajajIzcalliNavigation: CRMNavigationItemConfig[] = [
  {
    id: "home",
    label: "Inicio",
    route: "/crm",
    sectionId: "sales",
    order: 1,
    status: "active",
    visible: true,
  },
  {
    id: "leads",
    label: "Prospectos",
    route: "/crm/prospectos",
    moduleId: "leads",
    sectionId: "sales",
    order: 2,
    status: "active",
    visible: true,
  },
  {
    id: "contacts",
    label: "Clientes",
    route: "/crm/clientes",
    moduleId: "contacts",
    sectionId: "sales",
    order: 3,
    status: "active",
    visible: true,
  },
  {
    id: "deals",
    label: "Tratos",
    route: "/crm/tratos",
    moduleId: "deals",
    sectionId: "sales",
    order: 4,
    status: "active",
    visible: true,
  },
  {
    id: "quotes",
    label: "Cotizaciones",
    route: "/crm/cotizaciones",
    moduleId: "quotes",
    sectionId: "sales",
    order: 5,
    status: "active",
    visible: true,
  },
  {
    id: "sales-orders",
    label: "Órdenes de venta",
    route: "/crm/ordenes-de-venta",
    moduleId: "sales-orders",
    sectionId: "sales",
    order: 6,
    status: "active",
    visible: true,
  },
  {
    id: "motorcycles",
    label: "Motocicletas",
    route: "/crm/motocicletas",
    moduleId: "motorcycles",
    sectionId: "commercial-operation",
    order: 1,
    status: "active",
    visible: true,
  },
  {
    id: "promotions",
    label: "Promociones",
    route: "/crm/promociones",
    moduleId: "promotions",
    sectionId: "commercial-operation",
    order: 2,
    status: "active",
    visible: true,
  },
  {
    id: "agenda",
    label: "Agenda",
    route: "/crm/agenda",
    moduleId: "activities",
    sectionId: "commercial-operation",
    order: 3,
    status: "active",
    visible: true,
  },
  {
    id: "documents",
    label: "Documentos",
    route: "/crm/documentos",
    moduleId: "documents",
    sectionId: "commercial-operation",
    order: 4,
    status: "active",
    visible: true,
  },
  {
    id: "campaigns",
    label: "Campañas",
    route: "/crm/campanas",
    moduleId: "campaigns",
    sectionId: "administration",
    order: 1,
    status: "active",
    visible: true,
    allowedRoles: ["owner", "admin", "manager"],
  },
  {
    id: "users",
    label: "Usuarios",
    route: "/crm/usuarios",
    moduleId: "users",
    sectionId: "administration",
    order: 2,
    status: "active",
    visible: true,
    allowedRoles: ["owner", "admin", "manager"],
  },
  {
    id: "settings",
    label: "Configuración",
    route: "/crm/configuracion",
    sectionId: "administration",
    order: 3,
    status: "active",
    visible: true,
    allowedRoles: ["owner", "admin", "manager"],
  },
  {
    id: "inventory",
    label: "Inventario",
    sectionId: "coming-soon",
    order: 1,
    status: "coming-soon",
    visible: true,
  },
  {
    id: "after-sales",
    label: "Postventa",
    sectionId: "coming-soon",
    order: 2,
    status: "coming-soon",
    visible: true,
  },
  {
    id: "services",
    label: "Servicios",
    sectionId: "coming-soon",
    order: 3,
    status: "coming-soon",
    visible: true,
  },
  {
    id: "billing",
    label: "Facturación",
    sectionId: "coming-soon",
    order: 4,
    status: "coming-soon",
    visible: true,
  },
];