"use client";
import { useEffect,useState,type FormEvent } from "react";
type Data={branch:string;timezone:string;from:string;to:string;counts:Record<string,number>;daily:Array<{day:string;count:number}>;total:number;pets:number;returningTutors:number;tutors:number;averageDaycareHours:number|null;payments:Array<{currency:string;total:string;count:number;method:string}>|null;packages:Array<{unit:string;consumed:number}>|null;updatedAt:string};
const kinds=[{key:"daycare",label:"Guarderías",color:"bg-cyan-500"},{key:"boarding",label:"Pensiones",color:"bg-indigo-500"},{key:"grooming",label:"Grooming",color:"bg-fuchsia-500"},{key:"veterinary",label:"Consultas veterinarias",color:"bg-emerald-500"}];
export default function PetsAnalytics(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[period,setPeriod]=useState(""),[revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();void fetch(`/api/crm/pets/analytics${period}`,{signal:controller.signal,cache:"no-store"}).then(async response=>{const body=await response.json() as {success:boolean;data?:Data;error?:string};if(!response.ok||!body.success||!body.data)throw new Error(body.error||"No fue posible consultar indicadores.");if(!controller.signal.aborted){setData(body.data);setError("");}}).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[period,revision]);
 function filter(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);setLoading(true);setPeriod(`?from=${values.get("from")}&to=${values.get("to")}`);setRevision(value=>value+1);}
 const max=Math.max(1,...(data?.daily.map(day=>day.count)||[]));
 return <main className="space-y-6 pb-6"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-700">Datara Pets · Analytics</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Conoce el ritmo de tu negocio.</h1><p className="mt-2 text-sm text-slate-500">{data?.branch||"Sucursal activa"} · Servicios, recurrencia y cobros.</p></div>{data&&<form onSubmit={filter} className="flex flex-wrap items-end gap-2"><label className="text-xs text-slate-600">Desde<input key={`from-${data.from}`} name="from" type="date" defaultValue={data.from} required className="mt-1 block rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"/></label><label className="text-xs text-slate-600">Hasta<input key={`to-${data.to}`} name="to" type="date" defaultValue={data.to} required className="mt-1 block rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"/></label><button disabled={loading} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{loading?"Consultando…":"Aplicar"}</button></form>}</header>
 {error&&<p role="alert" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{error}{data&&" Se conserva el último periodo consultado correctamente."}</p>}{loading&&!data&&<p role="status">Cargando indicadores…</p>}
 {data&&<><p className="text-xs text-slate-500">Periodo mostrado: {data.from} — {data.to} · Días completos en {data.timezone}. Solo módulos autorizados.</p>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{label:"Atenciones registradas",value:data.total,detail:"Estancias finalizadas, grooming terminado y consultas",tone:"from-cyan-100 to-white"},{label:"Mascotas atendidas",value:data.pets,detail:"Mascotas distintas en el periodo",tone:"from-indigo-100 to-white"},{label:"Tutores que regresaron",value:data.returningTutors,detail:"Dos o más atenciones en el periodo",tone:"from-violet-100 to-white"},{label:"Guardería promedio",value:data.averageDaycareHours===null?"—":`${data.averageDaycareHours.toFixed(1)} h`,detail:"Duración de estancias de guardería finalizadas",tone:"from-emerald-100 to-white"}].map(card=><section key={card.label} className={`rounded-3xl border border-white bg-gradient-to-br ${card.tone} p-5 shadow-sm`}><h2 className="text-sm font-medium text-slate-600">{card.label}</h2><p className="my-3 text-4xl font-semibold tracking-tight text-slate-950">{card.value}</p><p className="text-xs text-slate-500">{card.detail}</p></section>)}</div>
 <div className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-950">Actividad por día</h2><p className="mt-1 text-xs text-slate-500">Cantidad de atenciones · no representa ingresos</p><div className="mt-6 flex h-44 items-end gap-1" role="img" aria-label={`Atenciones diarias: ${data.daily.map(day=>`${day.day}: ${day.count}`).join(', ')}`}>{data.daily.map(day=><div key={day.day} title={`${day.day}: ${day.count} atenciones`} className="flex h-full min-w-0 flex-1 items-end"><div style={{height:day.count?`${day.count/max*100}%`:"2px"}} className={`w-full rounded-t-sm ${day.count?"bg-gradient-to-t from-blue-600 to-cyan-400":"bg-slate-100"}`}/></div>)}</div><div className="mt-3 flex justify-between text-xs text-slate-400"><span>{data.from}</span><span>{data.to}</span></div>{!data.total&&<p className="mt-4 text-sm text-slate-500">Todavía no hay atenciones registradas en este periodo.</p>}<details className="mt-4 text-xs text-slate-500"><summary className="cursor-pointer">Ver cantidades por fecha</summary><div className="mt-2 max-h-40 overflow-auto">{data.daily.map(day=><p key={day.day}>{day.day}: {day.count}</p>)}</div></details></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-950">Atenciones por servicio</h2><div className="mt-6 space-y-5">{kinds.filter(kind=>kind.key in data.counts).map(kind=><div key={kind.key}><div className="mb-2 flex justify-between text-sm"><span className="text-slate-600">{kind.label}</span><span className="font-semibold">{data.counts[kind.key]}</span></div><div className="h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${kind.color}`} style={{width:`${data.total?data.counts[kind.key]/data.total*100:0}%`}}/></div></div>)}</div><p className="mt-6 text-xs text-slate-500">Guardería y pensión se clasifican al salir. Grooming cuenta órdenes, no cada baño o corte dentro de una misma orden.</p></section></div>
 <div className="grid gap-5 lg:grid-cols-2">{data.payments!==null&&<section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Cobros recibidos</h2><p className="mt-1 text-xs text-slate-500">Pagos vigentes de la sucursal por fecha de recepción. Incluye venta de productos y paquetes; excluye pagos cancelados.</p>{!data.payments.length?<p className="mt-5 text-sm text-slate-500">Sin cobros en el periodo.</p>:<div className="mt-5 space-y-3">{[...new Set(data.payments.map(p=>p.currency))].map(currency=><div key={currency} className="rounded-xl bg-emerald-50 p-4"><p className="text-xs font-semibold text-emerald-800">Total {currency}</p><p className="text-2xl font-semibold text-emerald-950">{(data.payments||[]).filter(p=>p.currency===currency).reduce((sum,p)=>sum+Number(p.total),0).toLocaleString("es-MX",{minimumFractionDigits:2,maximumFractionDigits:2})}</p></div>)}{data.payments.map(p=><div key={`${p.currency}-${p.method}`} className="flex justify-between gap-3 text-sm"><span className="text-slate-500">{({cash:"Efectivo",card:"Tarjeta",transfer:"Transferencia"} as Record<string,string>)[p.method]||p.method} · {p.count} pagos</span><span>{Number(p.total).toLocaleString("es-MX")} {p.currency}</span></div>)}</div>}</section>}
 {data.packages!==null&&<section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Uso de paquetes</h2><p className="mt-1 text-xs text-slate-500">Consumo neto vinculado a estancias de la sucursal. Descontar una unidad no genera otro ingreso.</p><div className="mt-5 grid grid-cols-3 gap-3">{[{key:"access",label:"Accesos"},{key:"day",label:"Días"},{key:"night",label:"Noches"}].map(unit=><div key={unit.key} className="rounded-2xl bg-indigo-50 p-4 text-center"><p className="text-3xl font-semibold text-indigo-950">{data.packages?.find(p=>p.unit===unit.key)?.consumed||0}</p><p className="mt-1 text-xs text-indigo-700">{unit.label}</p></div>)}</div><p className="mt-5 text-xs text-slate-500">Puede incluir devoluciones registradas en el periodo. No incluye ajustes sin estancia asociada.</p></section>}</div>
 <p className="text-xs text-slate-400">Actualizado {new Date(data.updatedAt).toLocaleTimeString("es-MX",{timeZone:data.timezone,hour:"2-digit",minute:"2-digit"})} · No se muestran proyecciones ni datos de ejemplo.</p></>}
 </main>;
}
